api_platform:
  formats:
    json: [ 'application/json' ]
    jsonld: [ 'application/ld+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
    html: [ 'text/html' ]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header