version: "3.4"

# Production environment override
services:
  php:
    env_file:
      - .env.prod.local
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      APP_ENV: prod
      # TODO: add jwt keys
      
  caddy:
    env_file:
      - .env.prod.local
    environment:
      SERVER_NAME: 'localhost, api.game7app.com, 54.174.176.86,'
