name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Build and run Docker container on EC2 instance
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ vars.SERVER_USER }}@${{ vars.SERVER_PUBLIC_IP }} "\
            eval \"$(ssh-agent -s)\" && \
            ssh-add ~/.ssh/id_ed25519 -p ${{ secrets.GIT_SSH_PASSPHRASE }} && \
            git-force-clone git@github.com:Game7-ESGI-2023-PA/game7-api.git game7-api && \
            ./start_prod.sh ${{ secrets.APP_SECRET }} ${{ secrets.DATABASE_URL }}"
        
