name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Build and run Docker container on EC2 instance
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ vars.SERVER_PUBLIC_IP }} "\
            ls && \
            pwd
